server:
  port: 8080
spring:
  application:
    name: sports-info-backend
  datasource:
    url: jdbc:postgresql://localhost:5432/sportsdb
    driverClassName: org.postgresql.Driver
    username: sports
    password: sports
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    locations: classpath:db/migration

jwt:
  secret: c3VwZXItc2VjcmV0LXN1cGVyLXNlY3JldC1zdXBlci1zZWNyZXQxMjM0NTY3OA==
  expiration: 86400000

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    org.springframework.security: INFO
    org.hibernate.SQL: INFO
